repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3 
        stages: [commit]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: [--force-single-line-imports, --force-sort-within-sections]
        stages: [commit]

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        stages: [commit]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        stages: [commit]

  - repo: https://github.com/paul-ko/simple-commit-message-format
    rev: "1.2.0"
    hooks:
      - id: check-msg-format-on-push
        stages: [push]
