import csv
from pathlib import Path

from broguedb.app.data import CatalogObject


def read_file(path: Path) -> list[CatalogObject]:
    out = []
    with path.open(encoding="UTF-8", newline="") as f:
        reader = csv.reader(f)
        next(reader)  # skip the header line generated by BrogueCE
        for line in reader:
            # Read empty fields as None, not as empty strings.
            line = [None if ln == "" else ln for ln in line]
            out.append(CatalogObject.from_csv_row(line))
    return out
